<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Поиск");
?>

<section class="shopSearch">
<div class="container">
	<div class="row">
		<hr>
		<div class="text-center">
			<div class="shopSearch__title">ПОИСК</div>
		</div>
	</div>

<?$APPLICATION->IncludeComponent(
	"bitrix:catalog.search",
	"search_catalog",
	Array(
		"ACTION_VARIABLE" => "action",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"BASKET_URL" => "/personal/basket.php",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"CHECK_DATES" => "N",
		"CONVERT_CURRENCY" => "N",
		"DETAIL_URL" => "",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_COMPARE" => "N",
		"DISPLAY_TOP_PAGER" => "N",
		"ELEMENT_SORT_FIELD" => "sort",
		"ELEMENT_SORT_FIELD2" => "id",
		"ELEMENT_SORT_ORDER" => "asc",
		"ELEMENT_SORT_ORDER2" => "desc",
		"HIDE_NOT_AVAILABLE" => "N",
		"IBLOCK_ID" => "25",
		"IBLOCK_TYPE" => "catalog",
		"LINE_ELEMENT_COUNT" => "1",
		"NO_WORD_LOGIC" => "N",
		"OFFERS_LIMIT" => "5",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => "pagenavigation_catalog",
		"PAGER_TITLE" => "Товары",
		"PAGE_ELEMENT_COUNT" => "10",
		"PRICE_CODE" => array("BASE","Оптовая"),
		"PRICE_VAT_INCLUDE" => "Y",
		"PRODUCT_ID_VARIABLE" => "id",
		"PRODUCT_PROPERTIES" => array(),
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PRODUCT_QUANTITY_VARIABLE" => "quantity",
		"PROPERTY_CODE" => array("IP","BREND","VID_SVETILNIKA","VYGRUZHAT_NA_SAYT","BLOG_POST_ID","SALE","CML2_ARTICLE","CML2_BASE_UNIT","ON_MAIN_PAGE","VYSOTA_KOROBKI","RECOMMENDED_DISIGNER","BLOG_COMMENTS_CNT","BEST_OFFER","CML2_MANUFACTURER","CML2_TRAITS","CML2_TAXES","CML2_ATTRIBUTES","HIT","SHOW_ROOM","CML2_BAR_CODE","VYSOTA_SVETILNIKA","GRUPPA_NA_SAYTE","GRUPPA_TOVARA_AVS","DIAMETR_SVETILNIKA","DLINA_KOROBKI","DLINA_SVETILNIKA","IZGOTOVITEL","INDEKS_MOSKVA","INDEKS_PITER","KOD_TAMOZHENNOY_GRUPPY","KOLICHESTVO_LAMP","KOLICHESTVO_PATRONOV","LAMPAVKOMPLEKTE","MATERIAL_ARMATURY","MATERIAL_DLYA_INVOYSA","MATERIAL_PLAFONA_DEKORA","MINIMALNOE_KOLICHESTVO_V_UPAKOVKE","MOSHCHNOST","NAIMENOVANIE_DLYA_SAYTA","NAPRYAZHENIE","NOVINKA","NOMER_SERTIFIKATA","NOMERBLANKASERTIFIKATA","ORGAN_PO_SERTIFIKATSII","PATRON","PORYADOK_SORTIROVKI_NA_SAYTE","PRIMECHANIE","RASPRODAZHA","SEMEYSTVO","SENSORNOE_VKLYUCHENIE","SERIYA","SERTIFIKATDEYSTVITELENDO","SERTIFIKATDEYSTVITELENS","STEKLO","STIL_SVETILNIKA","STRANITSAKATALOGARUS","TAMOZHENNAYA_GRUPPA","TIP_LAMPY","TIP_LAMPY_ANGLIYSKIY","TIP_SVETILNIKA","TIP_SVETILNIKA_ANGLIYSKIY","TIP_SVETILNIKA_UKRAINSKIY","TOVARNAYA_GRUPPA","TREBUET_SERTIFIKATSII","TSVET_ARMATURY","TSVET_PLAFONA","TSVET_FONA_NA_SAYTE","SHIRINA_KOROBKI","SHIRINA_SVETILNIKA","VES_NETTO","V_KOROBKE_NESKOLKO_SHTUK","VYKLYUCHATEL_V_KOMPLEKTE","DLINATSEPIILISHNURA","KLASS_ENERGOEFFEKTIVNOSTI","KOMPLEKT_KOROBOK","KREPLENIE","MONTAZHNOE_OTVERSTIE","RAZDELNOE_VKLYUCHENIE","SVETOVOY_POTOK","TOP_ASSORTIMENT","_3D_MODEL","DIAMETR_VREZNOGO_OTVERSTIYA_SM","_PRIMECHANIYA","_VID_IZDELIYA","_IZGOTOVITEL","_LAMPA","_MATERIAL","_RAZMERY","_TOVARINTERNETMAGAZINA","MATERIAL","NE_KONTROLIROVAT_UPAKOVKU","SROK_SLUZHBY",""),
		"RESTART" => "N",
		"SECTION_ID_VARIABLE" => "SECTION_ID",
		"SECTION_URL" => "",
		"SHOW_PRICE_COUNT" => "1",
		"USE_LANGUAGE_GUESS" => "Y",
		"USE_PRICE_COUNT" => "N",
		"USE_PRODUCT_QUANTITY" => "N"
	)
);?>

	</div>
	</section>
<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>